# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/Messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app/proto/Messages.proto", :syntax => :proto3) do
    add_message "rpc.GetMessageReq" do
      optional :id, :uint64, 1
    end
    add_message "rpc.GetMessageResp" do
      optional :id, :uint64, 1
      optional :name, :string, 2
    end
  end
end

module Rpc
  GetMessageReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetMessageReq").msgclass
  GetMessageResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("rpc.GetMessageResp").msgclass
end
