# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: app/proto/Messages.proto for package 'rpc'

require 'grpc'
require_relative './Messages_pb'

module Rpc
  module Messages
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'rpc.Messages'

      rpc :GetMessage, ::Rpc::GetMessageReq, ::Rpc::GetMessageResp
    end

    Stub = Service.rpc_stub_class
  end
end
